### ISSUE TITLE
Enhancement Request: Exclude files config option

### ISSUE THREAD

**Issue by erlgry** [achiku/wbs#1]
Nice work.

It will be nice to have another config option to exclude files just like the option to exclude directories. In my case as part of my build process I generate some files using go generate. This causes wbs to go in a perpetual loop.

So support for excluding files file *_gen.go would be really handy. That's the only thing preventing me from using this tool.

**Comment by achiku** [comment]
@erlgry Yeah, that's necessary feature when we use `go generate`. I'll add that feature soon!

**Comment by achiku** [comment]
@erlgry I added feature and pushed to master. Could you try it out? You just need to add the following to your toml config.

```
watch_file_exclude_pattern = ["*_gen.go"]
```

https://github.com/achiku/wbs/commit/f3a9d09650a454ae605abd39046e1da655df8293

**Comment by erlgry** [comment]
Thanks @achiku . Perhaps I am doing something wrong. But I can't seem to make it work. Here is the conf I am using:

root_path = "."

watch_target_dirs = ["."]
watch_exclude_dirs = [".git", "vendor", "tmp","build"]
watch_file_ext = [".go", ".tmpl", ".html"]
watch_file_exclude_pattern = ["bindata.go", "bindata_assetfs.go"]
build_target_dir = "."
build_target_name = "myapp"
build_command = "make"
build_options = ["release-fast"]
start_options = [""]

For some reason the wbs keeps getting events for changes into bindata.go and bindata_assetfs.go and keeps trying to restart the build. Here is a little massaged output from the console:

21:00:17 builder     |
...build output...blah
21:00:17 builder     | build completed
21:00:17 runner      | starting server: myapp [-user abc -pwd def]
21:00:17 runner      | server started: PID 2753
21:00:17 main        | file modified: "web/bindata_assetfs.go": WRITE|CHMOD
21:00:17 builder     | starting build: make [release-fast -o myapp]
21:00:17 runner      | 2016/02/09 21:00:17 Starting server on port 8000
21:00:17 runner      | 2016/02/09 21:00:17 Error starting the server listen tcp :8000: bind: address already in use

**Comment by achiku** [comment]
@erlgry Could you try the following conf? I also updated README to describe configuration more in depth.

``` toml
watch_file_exclude_pattern = ["web/bindata.go", "web/bindata_assetfs.go"]
```

**Comment by erlgry** [comment]
@achiku Sorry it took a little time to get back to it. Thanks for creating this tool and making the fix. I am now using wbs and for my use-case it is working pretty well. I'v got tons of things going on my build side including javascript compilation, go generate, embedding etc. and wbs is handling it very gracefully. 

Couple of comments/questions:
1 How do I use environment vars in the start options?
For example, Instead of
start_options = ["-dbuser", "abc", "-dbpwd", "def"]
I would like to use something like:
#start_options = ["-dbuser", '$POSTGRES_USER', "-dbpwd", '$POSTGRES_PASSWORD']

2 It would be nice if there was no expectation of bin directory. Instead if we could simply specify any arbitrary path to the command. In my case, for example the output of my makefile build is copied to $GOPATH/bin. It would be nice to simply run the command from there. Minor nit

**Comment by achiku** [comment]
@erlgry Thank you for the feedback!  I'll answer to the questions below.
1. Environmental variable use in start/build commands
   It's currently impossible to use env vars in those commands, but it should be just few lines of fix to enable that feature, and I think it's good to have that feature. So, I'll create new issue for that.
2. Arbitrary path for binary
   It's possible to set arbitrary path for binary if you set `build_target_dir`, but currently env var can't be used in this configuration, and thus impossible to use `$GOPATH/bin` as value of `build_target_dir`. After implementing (1), it will be really easy to extend env var handling to `build_target_dir`. I'll add that feature too.

**Comment by erlgry** [comment]
Thanks @achiku

**Comment by achiku** [comment]
@erlgry done with env var handling! Check it out, and if you find any problem, just let me know.
