### ISSUE TITLE
does not work on Vim

### ISSUE THREAD

**Issue by moqada** [achiku/wbs#5]
it does not work when starting wbs and editing file on vim.
but, it works when set `nowritebackup`.

see: https://github.com/fsnotify/fsnotify/issues/17

**Comment by achiku** [comment]
@moqada Thank you for opening issue! As we discussed in the office, it is quite difficult to fix fsnotify at this point of time, so I keep this issue open. Below is temporary workaround config for vim to avoid this problem.

```
:set nobackup
:set nowritebackup
```

**Comment by achiku** [comment]
It's been while but, this newly added option works for me.

https://github.com/achiku/wbs/pull/12
